Repository NangoHQ/nango, pull requests merged in 2024-06, with the labels that each got.

#2234 feat(integrations): add support for marketo
  docs-v2/integrations/all/marketo.mdx
  docs-v2/integrations/marketing.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/marketo.svg
Labels: api

#2251 feat(integrations): add support for highlevel white-label
  docs-v2/integrations/all/highlevel.mdx
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/highlevel-white-label.svg
Labels: api

#2223 feat(integrations): add support for datev
  docs-v2/integrations/all/datev.mdx
  docs-v2/integrations/hr.mdx
  docs-v2/integrations/legal.mdx
  docs-v2/integrations/payroll.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/datev.svg
Labels: api

#2271 feat(integrations): add support for vimeo
  docs-v2/integrations/all/vimeo.mdx
  docs-v2/integrations/video.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/vimeo-basic.svg
  packages/webapp/public/images/template-logos/vimeo.svg
Labels: api

#2265 feat(integrations): add support for instantly api key
  docs-v2/integrations/all/instantly.mdx
  docs-v2/integrations/communication.mdx
  docs-v2/integrations/integration-templates/instantly.mdx
  docs-v2/integrations/marketing.mdx
  docs-v2/mint.json
  integration-templates/instantly/actions/set-campaign-name.ts
  integration-templates/instantly/nango.yaml
  packages/shared/flows.yaml
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/instantly.svg
Labels: api, template

#2287 feat(integrations): add support for fireflies
  docs-v2/integrations/all/fireflies.mdx
  docs-v2/integrations/analytics.mdx
  docs-v2/integrations/communication.mdx
  docs-v2/integrations/integration-templates/fireflies.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  integration-templates/fireflies/actions/add-to-live.ts
  integration-templates/fireflies/nango.yaml
  packages/shared/flows.yaml
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/fireflies.svg
Labels: api, template

#2293 feat(integrations): add support for microsoft power bi
  docs-v2/integrations/all/microsoft-power-bi.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/microsoft-power-bi.svg
Labels: api

#2306 fix(webhooks): [nan-1178] disable automatic opt in for webhook settings
  packages/webhooks/lib/auth.ts
  packages/webhooks/lib/sync.ts
Labels: service: server, service: jobs

#2324 fix(webhooks): [nan-1204] make queryTimestamp always present
  packages/webhooks/lib/sync.ts
Labels: service: jobs

#2333 fix(slack): only notify success if it has refreshed (again)
  packages/shared/lib/services/connection.service.ts
Labels: service: server

#2330 feat(integrations): add support for unanet
  docs-v2/integrations/accounting.mdx
  docs-v2/integrations/all/unanet.mdx
  docs-v2/integrations/crm.mdx
  docs-v2/integrations/erp.mdx
  docs-v2/mint.json
  packages/shared/lib/services/proxy.service.ts
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/unanet.svg
Labels: service: server, service: runner

#2332 chore(logs.v1): remove from persist
  packages/logs/lib/client.ts
  packages/logs/lib/index.ts
  packages/node-client/lib/index.ts
  packages/node-client/lib/types.ts
  packages/persist/lib/controllers/persist.controller.ts
  packages/persist/lib/server.integration.test.ts
  packages/persist/lib/server.ts
  packages/server/lib/controllers/v1/logs/getOperation.integration.test.ts
  packages/server/lib/controllers/v1/logs/searchFilters.integration.test.ts
  packages/server/lib/controllers/v1/logs/searchMessages.integration.test.ts
  packages/server/lib/controllers/v1/logs/searchOperations.integration.test.ts
  packages/server/lib/routes.integration.test.ts
  packages/shared/lib/seeders/activity.seeder.ts
Labels: service: persist

#2319 feat(webhooks): [nan-1142] update options on environment settings to allow more use settings
  package-lock.json
  packages/node-client/lib/types.ts
  packages/node-client/package.json
  packages/node-client/tsconfig.json
  packages/server/lib/controllers/environment.controller.ts
  packages/server/lib/controllers/v1/environment/webhook/patchSettings.ts
  packages/server/lib/controllers/v1/environment/webhook/updatePrimaryUrl.ts
  packages/server/lib/controllers/v1/environment/webhook/updateSecondaryUrl.ts
  packages/server/lib/hooks/hooks.ts
  packages/server/lib/routes.ts
  packages/server/lib/webhook/webhook.manager.ts
  packages/shared/lib/index.ts
  packages/shared/lib/services/environment.service.ts
  packages/shared/lib/services/external-webhook.service.ts
  packages/shared/lib/services/notification/webhook.service.ts
  packages/shared/lib/services/notification/webhook.service.unit.test.ts
  packages/shared/lib/services/sync/run.service.ts
  packages/types/lib/environment/api/webhook.ts
  packages/types/lib/environment/db.ts
  packages/types/lib/index.ts
  packages/types/lib/webhooks/api.ts
  packages/utils/lib/vitest.d.ts
  packages/webapp/src/App.tsx
  packages/webapp/src/pages/Environment/Settings.tsx
  packages/webapp/src/pages/Environment/WebhookCheckboxes.tsx
  packages/webapp/src/utils/api.tsx
  packages/webhooks/lib/auth.ts
  packages/webhooks/lib/auth.unit.test.ts
  packages/webhooks/lib/enums.ts
  packages/webhooks/lib/forward.ts
  packages/webhooks/lib/forward.unit.test.ts
  packages/webhooks/lib/index.ts
  packages/webhooks/lib/sync.ts
  packages/webhooks/lib/sync.unit.test.ts
  packages/webhooks/lib/types.ts
  packages/webhooks/lib/utils.ts
  scripts/publish.sh
  tests/setupFiles.ts
  vite.config.ts
Labels: service: server, service: jobs

#2415 feat(tba-integration): [nan-1259] support netsuite tba authorization
  docs-v2/integrate/guides/authorize-an-api.mdx
  packages/cli/lib/services/__snapshots__/model.service.unit.test.ts.snap
  packages/frontend/lib/index.ts
  packages/node-client/lib/types.ts
  packages/server/lib/controllers/auth/tba.ts
  packages/server/lib/controllers/oauth.controller.ts
  packages/server/lib/controllers/proxy.controller.ts
  packages/server/lib/helpers/tba.ts
  packages/server/lib/routes.ts
  packages/server/lib/utils/hmac.ts
  packages/shared/lib/models/Auth.ts
  packages/shared/lib/models/Connection.ts
  packages/shared/lib/sdk/sync.ts
  packages/shared/lib/services/proxy.service.ts
  packages/shared/lib/services/proxy.service.unit.test.ts
  packages/shared/lib/utils/analytics.ts
  packages/shared/providers.yaml
  packages/types/lib/auth/api.ts
  packages/types/lib/auth/http.api.ts
  packages/types/lib/connection/db.ts
  packages/types/lib/index.ts
  packages/types/lib/integration/template.ts
  packages/utils/lib/auth.ts
  packages/utils/lib/index.ts
  packages/webapp/public/images/template-logos/netsuite-tba.svg
  packages/webapp/src/pages/Connection/Create.tsx
  packages/webapp/src/pages/Integration/AuthSettings.tsx
  packages/webapp/src/types.ts
  scripts/validation/providers/schema.json
Labels: high priority
