Repository NangoHQ/nango, pull requests merged in 2024-05, with the labels that each got.

#2102 feat(integrations): add support for posthog api
  docs-v2/integrations/all/posthog.mdx
  docs-v2/integrations/dev-tools.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/posthog.svg
Labels: api

#2109 feat(integrations):add support for wealthbox
  docs-v2/integrations/all/wealthbox.mdx
  docs-v2/integrations/crm.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/wealthbox.svg
Labels: api

#2083 feat(integrations): add support for lessonly api
  docs-v2/integrations/all/lessonly.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/lessonly.svg
Labels: api

#2092 feat(integrations): add support for envoy api
  docs-v2/integrations/all/envoy.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/envoy.svg
Labels: api

#2084 feat(integrations): add support for pivotaltracker api
  docs-v2/integrations/all/pivotaltracker.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/pivotaltracker.svg
Labels: api

#2082 feat(integrations): add support for dialpad
  docs-v2/integrations/all/dialpad.mdx
  docs-v2/integrations/communication.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/dialpad.svg
Labels: api

#2145 feat(api): [NAN-793] bulk metadata update api
  docs-v2/mint.json
  docs-v2/reference/api/connection/set-metadata-legacy.mdx
  docs-v2/reference/api/connection/set-metadata.mdx
  docs-v2/reference/api/connection/update-metadata-legacy.mdx
  docs-v2/reference/api/connection/update-metadata.mdx
  docs-v2/reference/sdks/node.mdx
  docs-v2/spec.yaml
  package-lock.json
  packages/cli/lib/services/dryrun.service.ts
  packages/cli/package.json
  packages/node-client/bin/set-metadata.js
  packages/node-client/bin/update-metadata.js
  packages/node-client/lib/index.ts
  packages/node-client/lib/types.ts
  packages/server/lib/controllers/connection.controller.ts
  packages/server/lib/controllers/v1/connection/setMetadata.integration.test.ts
  packages/server/lib/controllers/v1/connection/setMetadata.ts
  packages/server/lib/controllers/v1/connection/updateMetadata.integration.test.ts
  packages/server/lib/controllers/v1/connection/updateMetadata.ts
  packages/server/lib/routes.ts
  packages/shared/lib/db/seeders/config.seeder.ts
  packages/shared/lib/db/seeders/connection.seeder.ts
  packages/shared/lib/models/Connection.ts
  packages/shared/lib/sdk/sync.ts
  packages/shared/lib/services/connection.service.integration.test.ts
  packages/shared/lib/services/connection.service.ts
  packages/shared/lib/services/proxy.service.unit.test.ts
  packages/shared/lib/services/sync/run.service.ts
  packages/shared/lib/utils/error.ts
  packages/types/lib/api.endpoints.ts
  packages/types/lib/connection/api/metadata.ts
  packages/types/lib/connection/db.ts
  packages/types/lib/index.ts
  scripts/publish.sh
Labels: service: server, service: node-client

#2175 feat(integrations): add support for woocommerce
  docs-v2/integrations/all/woocommerce.mdx
  docs-v2/integrations/design.mdx
  docs-v2/integrations/dev-tools.mdx
  docs-v2/integrations/ecommerce.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/woocommerce.svg
Labels: api

#2173 feat(server): [nan-869] email verification on signup
  packages/server/lib/clients/email.client.ts
  packages/server/lib/clients/workos.client.ts
  packages/server/lib/controllers/auth.controller.ts
  packages/server/lib/controllers/v1/account/getEmailByExpiredToken.ts
  packages/server/lib/controllers/v1/account/getEmailByUuid.ts
  packages/server/lib/controllers/v1/account/index.ts
  packages/server/lib/controllers/v1/account/resendVerificationEmailByEmail.ts
  packages/server/lib/controllers/v1/account/resendVerificationEmailByUuid.ts
  packages/server/lib/controllers/v1/account/signin.ts
  packages/server/lib/controllers/v1/account/signup.ts
  packages/server/lib/controllers/v1/account/signupWithToken.ts
  packages/server/lib/controllers/v1/account/validateEmailAndLogin.ts
  packages/server/lib/helpers/email.ts
  packages/server/lib/middleware/ratelimit.middleware.ts
  packages/server/lib/routes.ts
  packages/shared/lib/db/migrations/20240517171724_verified_flag.cjs
  packages/shared/lib/models/Admin.ts
  packages/shared/lib/services/user.service.ts
  packages/types/lib/account/api.ts
  packages/types/lib/index.ts
  packages/types/lib/user/api.ts
  packages/utils/lib/result.ts
  packages/webapp/src/App.tsx
  packages/webapp/src/pages/Account/EmailVerified.tsx
  packages/webapp/src/pages/Account/ForgotPassword.tsx
  packages/webapp/src/pages/Account/InviteSignup.tsx
  packages/webapp/src/pages/Account/ResetPassword.tsx
  packages/webapp/src/pages/Account/Signin.tsx
  packages/webapp/src/pages/Account/Signup.tsx
  packages/webapp/src/pages/Account/VerifyEmail.tsx
  packages/webapp/src/pages/Account/VerifyEmailByExpiredToken.tsx
  packages/webapp/src/utils/api.tsx
Labels: service: server

#2192 feat(integrations): add support for tremendous
  docs-v2/integrations/all/tremendous.mdx
  docs-v2/integrations/payment.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/tremendous-sandbox.svg
  packages/webapp/public/images/template-logos/tremendous.svg
Labels: api

#2200 feat(integrations): add support for wrike
  docs-v2/integrations/all/wrike.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/wrike.svg
Labels: api

#2201 feat(integrations): add support for signnow
  docs-v2/integrations/all/signnow.mdx
  docs-v2/integrations/legal.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/signnow-sandbox.svg
  packages/webapp/public/images/template-logos/signnow.svg
Labels: api

#2194 feat(integrations): add support for productboard
  docs-v2/integrations/all/productboard.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/productboard.svg
Labels: api

#2209 feat(integrations): add support for various mircosoft graph api services
  docs-v2/integrations/all/microsoft-entra-id.mdx
  docs-v2/integrations/all/microsoft.mdx
  docs-v2/integrations/all/one-note.mdx
  docs-v2/integrations/all/outlook.mdx
  docs-v2/integrations/all/sharepoint-online.mdx
  docs-v2/integrations/communication.mdx
  docs-v2/integrations/knowledge-base.mdx
  docs-v2/integrations/other.mdx
  docs-v2/integrations/productivity.mdx
  docs-v2/integrations/storage.mdx
  docs-v2/mint.json
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/microsoft-ads.svg
  packages/webapp/public/images/template-logos/microsoft-entra-id.svg
  packages/webapp/public/images/template-logos/microsoft.svg
  packages/webapp/public/images/template-logos/one-note.svg
  packages/webapp/public/images/template-logos/outlook.svg
  packages/webapp/public/images/template-logos/sharepoint-online.svg
Labels: api
