Repository NangoHQ/nango, pull requests merged in 2024-03, with the labels that each got.

#1841 [nan-544] allow optional params to be passed in and used
  packages/shared/lib/sdk/sync.integration.test.ts
  packages/shared/lib/sdk/sync.ts
Labels: service: runner

#1848 feature(integration): add support for lever-basic-sandbox
  docs-v2/integrations/all/lever.mdx
  packages/shared/providers.yaml
  packages/webapp/public/images/template-logos/lever-basic-sandbox.svg
Labels: api

#1857 feature(integration): add integration templates for zoho-mail
  integration-templates/zoho-mail/nango.yaml
  integration-templates/zoho-mail/zoho-mail-add-user.ts
  integration-templates/zoho-mail/zoho-mail-emails.ts
  integration-templates/zoho-mail/zoho-mail-send-email.ts
  packages/shared/flows.yaml
Labels: template
